version: "3.2"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:

### demo API ########################################
  demo-api:
    container_name: demo-api
    image: demo/api
    build:
      context: ./demo-api
    volumes:
      - ${DEMO_API}:${WEBDEVOPS_WEB_DOCUMENT_ROOT}${APP_CODE_CONTAINER_FLAG}
      - ${DEMO_PACKAGES}:${WEBDEVOPS_WEB_DOCUMENT_ROOT}/packages${APP_CODE_CONTAINER_FLAG}
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"
    environment:
      LOG_STDOUT: ${WEBDEVOPS_WEB_LOG_STDOUT}
      LOG_STDERR: ${WEBDEVOPS_WEB_LOG_STDERR}
    networks:
      - frontend
      - backend

